// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn2VduUrfg_OQNeqUzkGzGcZknKwpsUPY',
    appId: '1:588781537822:android:dae49411382e2d70dbbc0f',
    messagingSenderId: '588781537822',
    projectId: 'betatesting-532b4',
    storageBucket: 'betatesting-532b4.firebasestorage.app',
    measurementId: "G-FSHVX3TJ5N",
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDn2VduUrfg_OQNeqUzkGzGcZknKwpsUPY",
    authDomain: "betatesting-532b4.firebaseapp.com",
    projectId: "betatesting-532b4",
    storageBucket: "betatesting-532b4.firebasestorage.app",
    messagingSenderId: "588781537822",
    appId: "1:588781537822:web:9f35f0f30e19830edbbc0f",
    measurementId: "G-FSHVX3TJ5N"
  );
}